package com.poc.portfolio.utils;

public final class Constants {
  public static final String RESUME_FILENAME = "sudeep-resume.pdf";
  public static final String RESUME_FILE_PATH = "src/main/resources/static/file/" + RESUME_FILENAME;
  public static final String RESUME_MEDIA_TYPE = "application/pdf";
  public static final String YOUTUBE_ASSET_URL = "/assets/youtube.png";
  public static final String EMAIL_ASSET_URL = "/assets/email.png";
  public static final String LINKEDIN_ASSET_URL = "/assets/linkedin.png";
  public static final String GITHUB_ASSET_URL = "/assets/github.png";
  public static final String LEETCODE_ASSET_URL = "/assets/leetcode.png";
  public static final String YOUTUBE_URL = "https://www.youtube.com/@sudeep528";
  public static final String LINKEDIN_URL = "https://www.linkedin.com/in/sudeep-vishwakarma-/";
  public static final String GITHUB_URL = "https://github.com/sudeepv44";
  public static final String LEETCODE_URL = "https://leetcode.com/chantiwa/";
  public static final String LIBRBARY_ASSET_URL = "/assets/librbary.png";
  public static final String SECURE_FILE_UPLOAD_ASSET_URL = "/assets/secure-file-upload-project.jpeg";
  public static final String GEHU_ONLINE_ASSET_URL = "/assets/gehu-online.png";
  public static final String LIBRBARY = " Sudeep Portfolio ";
  public static final String SECURE_FILE_UPLOAD = "Secure File Upload";
  public static final String GEHU_ONLINE = "Texi Booking System";
  public static final String LIBRBARY_GITHUB_URL = "";
  public static final String LIBRBARY_LIVE_DEMO_URL = "";
  public static final String SECURE_FILE_UPLOAD_GITHUB_URL = "https://github.com/sudeepv44/TexiBooking_System";
  public static final String SECURE_FILE_UPLOAD_LIVE_DEMO_URL = "https://github.com/sudeepv44/TexiBooking_System";
  public static final String GEHU_ONLINE_GITHUB_URL = "https://sudeepv44.github.io/texibooking/";
  public static final String GEHU_ONLINE_LIVE_DEMO_URL = "https://sudeepv44.github.io/texibooking/";
  public static final String PROFILE_PIC_ASSET_URL = "/assets/profile-pic.png";
  public static final String ABOUT_PIC_ASSET_URL = "/assets/about-pic.png";
  public static final String EXPERIENCE_ASSET_URL = "/assets/experience.png";
  public static final String EDUCATION_ASSET_URL = "/assets/education.png";
  public static final String ARROW_ASSET_URL = "/assets/arrow.png";
  public static final String CHECKMARK_ASSET_URL = "/assets/checkmark.png";
  public static final String ORACLE_LOGO_URL = "/assets/oracle-logo.png";
  public static final String MACQUARIE_LOGO_URL = "/assets/mcq-logo.jpg";
  public static final String AMEX_LOGO_URL = "/assets/amex-logo.jpg";
  public static final String EY_LOGO_URL = "/assets/ey-logo.png";
  public static final String HSBC_LOGO_URL = "/assets/hsbc-logo.png";
  public static final String CAPGEMINI_LOGO_URL = "/assets/capg-logo.jpg";
  public static final String INFOSYS_LOGO_URL = "/assets/infosys-logo.jpg";
  public static final String POC_BANNER_URL = "/assets/poc-banner.png";
  public static final String MY_NAME = "Sudeep Vishwakarma";
  public static final int MY_EXPERIENCE_IN_YEARS = 1;
  public static final String MY_EMAIL_ID = "Sudeepv859@Gmail.com";
  public static final String MAIL_TO_EMAIL = "mailto:" + MY_EMAIL_ID;
}
